#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# MANAGE SCRIPT FAILURE
#=================================================

# Exit if an error occurs during the execution of the script
ynh_abort_if_errors

#=================================================
# LOAD SETTINGS
#=================================================
ynh_script_progression --message="Load settings" --weight=2

app=$YNH_APP_INSTANCE_NAME

final_path=$(ynh_app_setting_get $app final_path)
domain=$(ynh_app_setting_get $app domain)
appname=$(ynh_app_setting_get $app appname)
sql=$(ynh_app_setting_get $app sql)

#=================================================
# STANDARD BACKUP STEPS
#=================================================
# BACKUP THE APP MAIN DIR
#=================================================
ynh_script_progression --message="Backup the app main dir" --weight=2

CHECK_SIZE "$final_path"
ynh_backup "$final_path"

#=================================================
# BACKUP NGINX CONFIGURATION
#=================================================
ynh_script_progression --message="Backup nginx configuration"

ynh_backup "/etc/nginx/conf.d/$domain.d/$appname.conf"

#=================================================
# BACKUP PHP-FPM CONFIGURATION
#=================================================
ynh_script_progression --message="Backup php-fpm configuration"

ynh_backup "/etc/php/7.0/fpm/pool.d/$appname.conf"

#=================================================
# BACKUP THE MYSQL DATABASE
#=================================================
ynh_script_progression --message="Backup the mysql database" --weight=2

if [ $sql -eq 1 ];
then
	db_name=$(ynh_app_setting_get $app db_name)
	db_pwd=$(ynh_app_setting_get $app mysqlpwd)
	ynh_mysql_dump_db "$db_name" > db.sql
	CHECK_SIZE "db.sql"
fi

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Backup completed" --last
