#!/bin/bash

#=================================================
# GENERIC STARTING
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# MANAGE FAILURE OF THE SCRIPT
#=================================================

ynh_abort_if_errors	# Active trap pour arrêter le script si une erreur est détectée.

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================

domain=$YNH_APP_ARG_DOMAIN
path_url=$YNH_APP_ARG_PATH
admin=$YNH_APP_ARG_ADMIN
sql=$YNH_APP_ARG_SQL
is_public=$YNH_APP_ARG_IS_PUBLIC

app=$YNH_APP_INSTANCE_NAME

#=================================================
# CHECK IF THE APP CAN BE INSTALLED WITH THIS ARGS
#=================================================

parent_dir=/var/www/webapp_$admin
directory="${domain//-/_}_$(echo $path_url | cut -d '/' -f 2)"
appname=webapp_$directory
final_path=$parent_dir/$directory
# Pour cette application, app correspond au label, comme d'habitude. Mais pas au nom de l'application. appname contient le nom de l'application, dérivé du path.
# Vérifie que le dossier de destination n'est pas déjà utilisé.
if [ -e "$final_path" ]
then
	ynh_die "This path already contains a folder"
fi

# Normalize the url path syntax
path_url=$(ynh_normalize_url_path $path_url)

# Check web path availability
ynh_webpath_available $domain $path_url
# Register (book) web path
ynh_webpath_register $app $domain $path_url

#=================================================
# STORE SETTINGS FROM MANIFEST
#=================================================

ynh_app_setting_set $app domain $domain
ynh_app_setting_set $app path $path_url
ynh_app_setting_set $app is_public $is_public
ynh_app_setting_set $app appname $appname
ynh_app_setting_set $app ftp_user $admin
ynh_app_setting_set $app final_path $final_path
ynh_app_setting_set $app parent_dir $parent_dir
ynh_app_setting_set $app sql $sql

#=================================================
# STANDARD MODIFICATIONS
#=================================================
# SETUP SSOWAT
#=================================================

if [ $is_public -eq 1 ]
then
	ynh_app_setting_set $app skipped_uris "/"
fi

#=================================================
# SPECIFIC SETUP
#=================================================
# CREATE FINAL PATH
#=================================================

# Créer le dossier parent des webapp pour l'utilisateur
if test ! -d $parent_dir
then	# Créer le dossier parent uniquement si il n'existe pas
	mkdir $parent_dir
	# Set permissions
	chmod 755 -R $parent_dir
	chown -R root: $parent_dir
else
	ynh_print_info "Création du dossier $parent_dir ignorée, le dossier existe déjà." >&2
fi

# Copy files to the right place
mkdir -p $final_path
cp ../sources/index.html $final_path/
# Vérifie si pure-ftpd est déjà installé
if test -f /usr/sbin/pure-ftpd-ldap
then	# Si oui, vérifie si net2ftp est également installé.
	if test -d $parent_dir/netftp
	then
		# Change admin ID in configurations
		netftp_path=/ftp_webapp_$admin
		ynh_replace_string "__FTPUSER__" "$admin" ../sources/index_ftp.html
		ynh_replace_string "__HOST__" "$domain" ../sources/index_ftp.html
		ynh_replace_string "__NET2FTP__" "$netftp_path" ../sources/index_ftp.html
		ynh_replace_string "__PORT__" "$(cat /etc/pure-ftpd/conf/Bind)" ../sources/index_ftp.html
		cp ../sources/index_ftp.html $final_path/index.html	# Remplace l'index.html par celui intégrant les informations ftp
	fi
fi

#=================================================
# CREATE A SQL BDD
#=================================================

if [ $sql -eq 1 ]
then
	db_name=$(ynh_sanitize_dbid $appname)
	ynh_app_setting_set $app db_name $db_name
	ynh_mysql_setup_db $db_name $db_name
	echo "DB_NAME= $db_name" | tee "$final_path/db_info.txt"
	echo "DB_USER= $db_name" | tee -a "$final_path/db_info.txt"
	echo "DB_PASSWORD= $db_pwd" | tee -a "$final_path/db_info.txt"
	echo "DB_HOST= localhost" | tee -a "$final_path/db_info.txt"
fi

#=================================================
# CREATE DEDICATED USER
#=================================================

ynh_system_user_create $appname	# Créer un utilisateur système dédié à l'app

#=================================================
# PHP-FPM CONFIGURATION
#=================================================

# En raison de l'usage de $appname, il n'est pas possible d'utiliser ynh_fpm_config
finalphpconf="/etc/php5/fpm/pool.d/$appname.conf"
cp ../conf/php-fpm.conf "$finalphpconf"

ynh_replace_string "__NAMETOCHANGE__" "$appname" "$finalphpconf"
ynh_replace_string "__FINALPATH__" "$final_path" "$finalphpconf"
ynh_replace_string "__USER__" "$appname" "$finalphpconf"

chown root: "$finalphpconf"

finalphpini="/etc/php5/fpm/conf.d/20-$appname.ini"
cp ../conf/php-fpm.ini "$finalphpini"
chown root: "$finalphpini"

systemctl reload php5-fpm

#=================================================
# NGINX CONFIGURATION
#=================================================

# En raison de l'usage de $appname, il n'est pas possible d'utiliser ynh_nginx_config

finalnginxconf="/etc/nginx/conf.d/$domain.d/$appname.conf"
cp ../conf/nginx.conf "$finalnginxconf"

ynh_replace_string "__PATH__" "$path_url" "$finalnginxconf"
ynh_replace_string "__FINALPATH__" "$final_path" "$finalnginxconf"
ynh_replace_string "__APPNAME__" "$appname" "$finalnginxconf"

#=================================================
# GENERIC FINALISATION
#=================================================
# SECURING FILES AND DIRECTORIES
#=================================================

chmod 775 -R $final_path
chown -R $admin:$appname $final_path

#=================================================
# RELOAD NGINX
#=================================================

systemctl reload nginx

#=================================================
# SEND A README FOR THE ADMIN
#=================================================

if [ "$sql" != "0" ]
then
	sql_infos="
You ask for an database, please find here the informations about this SQL database.
$(cat "$final_path/db_info.txt")
"
else
	sql_infos=""
fi

message="This app is simply a blank web app container. You have to put your own app inside.
$sql_infos
Please put your files in this directory, $final_path

You can find a standard nginx configuration in $finalnginxconf and a standard php config in $finalphpconf and $finalphpini

If you facing an issue or want to improve this app, please open a new issue in this project: https://github.com/YunoHost-Apps/multi_webapp_ynh"

ynh_send_readme_to_admin "$message" "$admin"
