#!/bin/bash

#=================================================
# GENERIC STARTING
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================
ynh_script_progression --message="Load settings" --weight=3

app=$YNH_APP_INSTANCE_NAME

admin=$(ynh_app_setting_get $app ftp_user)
path=$(ynh_app_setting_get $app path)
domain=$(ynh_app_setting_get $app domain)
appname=$(ynh_app_setting_get $app appname)
sql=$(ynh_app_setting_get $app sql)
final_path=$(ynh_app_setting_get $app final_path)
parent_dir=$(ynh_app_setting_get $app parent_dir)

#=================================================
# STANDARD REMOVE
#=================================================
# REMOVE THE MYSQL DATABASE
#=================================================

if [ "$sql" -eq "1" ];
then
	ynh_script_progression --message="Remove the mysql database"
	db_name=$(ynh_app_setting_get $app db_name)
	# Remove a database if it exists, along with the associated user
	ynh_mysql_remove_db $db_name $db_name
fi

#=================================================
# REMOVE APP MAIN DIR
#=================================================
ynh_script_progression --message="Remove app main directory"

# Remove the app directory securely
ynh_secure_remove "$final_path"

#=================================================
# REMOVE NGINX CONFIGURATION
#=================================================
ynh_script_progression --message="Remove nginx configuration" --weight=2

# Use appname for FPM and nginx
app=$appname
# Remove the dedicated nginx config
ynh_remove_nginx_config

#=================================================
# REMOVE PHP-FPM CONFIGURATION
#=================================================
ynh_script_progression --message="Remove php-fpm configuration"

# Remove the dedicated php-fpm config
ynh_remove_fpm_config

#=================================================
# SPECIFIC REMOVE
#=================================================
# REMOVE THE PARENT DIR
#=================================================

# Check if the parent dir is empty. Which means that all webapps have been removed.
if [ -e "$parent_dir" ]
then
	if test -z "$(ls $parent_dir | head -n1)"
	then
		ynh_secure_remove $parent_dir
	fi
fi

#=================================================
# GENERIC FINALISATION
#=================================================
# REMOVE DEDICATED USER
#=================================================
ynh_script_progression --message="Remove the dedicated user" --weight=2

# Delete dedicated system user
ynh_system_user_delete $appname

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Deletion completed" --last
