#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

if [ ! -e _common.sh ]; then
	# Get the _common.sh file if it's not in the current directory
	cp ../settings/scripts/_common.sh ./_common.sh
	chmod a+rx _common.sh
fi
source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# MANAGE SCRIPT FAILURE
#=================================================

# Exit if an error occurs during the execution of the script
ynh_abort_if_errors

#=================================================
# LOAD SETTINGS
#=================================================

app=$YNH_APP_INSTANCE_NAME

final_path=$(ynh_app_setting_get $app final_path)
domain=$(ynh_app_setting_get $app domain)
appname=$(ynh_app_setting_get $app appname)
path_url=$(ynh_app_setting_get $app path)
sql=$(ynh_app_setting_get $app sql)
parent_dir=$(ynh_app_setting_get $app parent_dir)
admin=$(ynh_app_setting_get $app ftp_user)

#=================================================
# CHECK IF THE APP CAN BE RESTORED
#=================================================

ynh_webpath_available $domain $path_url \
	|| ynh_die "Path not available: ${domain}${path_url}"
test ! -d $final_path \
	|| ynh_die "There is already a directory: $final_path "

#=================================================
# STANDARD RESTORE STEPS
#=================================================
# RESTORE OF THE NGINX CONFIGURATION
#=================================================

ynh_restore_file "/etc/nginx/conf.d/$domain.d/$appname.conf"

#=================================================
# RESTORE OF THE MAIN DIR OF THE APP
#=================================================

if test ! -d $parent_dir
then	# Créer le dossier parent uniquement si il n'existe pas
	mkdir $parent_dir
	# Set permissions
	chmod 755 -R $parent_dir
fi
ynh_restore_file "$final_path"

#=================================================
# RESTORE OF THE SQL BDD
#=================================================

if [ $sql -eq 1 ];
then
	db_name=$(ynh_app_setting_get $app db_name)
	db_pwd=$(ynh_app_setting_get $app mysqlpwd)
	ynh_mysql_create_db $db_name $db_name $db_pwd
	ynh_mysql_connect_as $db_name $db_pwd $db_name < ./db.sql
fi

#=================================================
# RECREATE OF THE DEDICATED USER
#=================================================

ynh_system_user_create $appname	# Recreate the dedicated user, if not exist

#=================================================
# SECURING FILES AND DIRECTORIES
#=================================================

chown -R $admin:$appname $final_path

#=================================================
# RESTORE OF THE PHP-FPM CONFIGURATION
#=================================================

ynh_restore_file "/etc/php5/fpm/pool.d/$appname.conf"
ynh_restore_file "/etc/php5/fpm/conf.d/20-$appname.ini"

#=================================================
# GENERIC FINALISATION
#=================================================
# RELOAD NGINX AND PHP-FPM
#=================================================

systemctl reload php5-fpm
systemctl reload nginx
