#!/bin/bash

#=================================================
# GENERIC STARTING
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================

app=$YNH_APP_INSTANCE_NAME

is_public=$(ynh_app_setting_get $app is_public)
appname=$(ynh_app_setting_get $app appname)
db_name=$(ynh_app_setting_get $app db_name)

#=================================================
# CHECK VERSION
#=================================================

upgrade_type=$(ynh_check_app_version_changed)

#=================================================
# FIX OLD THINGS
#=================================================

if test -z "$appname"
then	# Si appname est vide, le nom de l'app est stocké sous l'ancien nom app
	appname=$(ynh_app_setting_get $app app)	# On Récupère l'information.
	ynh_app_setting_delete $app app	# On supprime l'ancienne information.
	ynh_app_setting_set $app appname $app	# Pour la remplacer par la nouvelle.
fi

if [ "$is_public" = "Yes" ]; then
	ynh_app_setting_set $app is_public 1	# Fixe is_public en booléen
	is_public=1
elif [ "$is_public" = "No" ]; then
	ynh_app_setting_set $app is_public 0
	is_public=0
fi

sql=$(ynh_app_setting_get $app sql)
if [ "$sql" = "Yes" ]; then
	ynh_app_setting_set $app sql 1	# Fixe sql en booléen
elif [ "$sql" = "No" ]; then
	ynh_app_setting_set $app sql 0
fi

if [ -z "$db_name" ]; then	# Si db_name n'est pas renseigné dans app setting
	db_name=$(ynh_sanitize_dbid $app)
	ynh_app_setting_set $app db_name $db_name
fi

#=================================================
# BACKUP BEFORE UPGRADE THEN ACTIVE TRAP
#=================================================

# Backup the current version of the app
ynh_backup_before_upgrade
ynh_clean_setup () {
	# restore it if the upgrade fails
	ynh_restore_upgradebackup
}
# Exit if an error occurs during the execution of the script
ynh_abort_if_errors

#=================================================
# SETUP SSOWAT
#=================================================

# Make app public if necessary
if [ $is_public -eq 1 ]
then
	ynh_app_setting_set $app skipped_uris "/"
fi
