#!/bin/bash

#=================================================
# GENERIC STARTING
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# RETRIEVE ARGUMENTS
#=================================================

app=${YNH_APP_INSTANCE_NAME:-$YNH_APP_ID}

sql=$(ynh_app_setting_get $app sql)
appname=$(ynh_app_setting_get $app appname)
final_path=$(ynh_app_setting_get $app final_path)

#=================================================
# CHECK IF ARGUMENTS ARE CORRECT
#=================================================

#=================================================
# CHECK IF AN ACTION HAS TO BE DONE
#=================================================

#=================================================
# SPECIFIC ACTION
#=================================================
# REMOVE THE PREVIOUS DATABASE
#=================================================

if [ $sql -eq 1 ]
then
	yunohost app action run $app remove_database
fi

#=================================================
# CREATE A NEW DATABASE
#=================================================

db_name=$(ynh_sanitize_dbid $appname)
# Reuse the previous password if existing
db_pwd=$(grep "DB_PASSWORD=" "$final_path/db_info.txt" | cut -d' ' -f2 2> /dev/null)

ynh_mysql_setup_db $db_name $db_name $db_pwd

echo "DB_NAME= $db_name" | tee "$final_path/db_info.txt"
echo "DB_USER= $db_name" | tee -a "$final_path/db_info.txt"
echo "DB_PASSWORD= $db_pwd" | tee -a "$final_path/db_info.txt"
echo "DB_HOST= localhost" | tee -a "$final_path/db_info.txt"

# Update the config of the app
ynh_app_setting_set $app sql 1
ynh_app_setting_set $app db_name $db_name
