#!/bin/bash

#=================================================
# GENERIC STARTING
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# RETRIEVE ARGUMENTS
#=================================================

app=${YNH_APP_INSTANCE_NAME:-$YNH_APP_ID}

sql=$(ynh_app_setting_get $app sql)

#=================================================
# CHECK IF ARGUMENTS ARE CORRECT
#=================================================

#=================================================
# CHECK IF AN ACTION HAS TO BE DONE
#=================================================

if [ $sql -eq 0 ]
then
	ynh_die "There's no database to remove." 0
fi

#=================================================
# SPECIFIC ACTION
#=================================================
# REMOVE THE DATABASE
#=================================================

db_name=$(ynh_app_setting_get $app db_name)
ynh_mysql_remove_db $db_name $db_name

# Update the config of the app
ynh_app_setting_set $app sql 0
